events {}

http {

    upstream notification_service {
        server notification-service:3003;
    }

    upstream location_service {
        server location-service:3004;
    }

    upstream delivery_service {
        server delivery-service:3005;
    }

    server {

        listen 80;

        # ───────── Notification Service ─────────

        location /api/notifications {

            proxy_pass http://notification_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ───────── Location Service ─────────

        location /api/location {

            proxy_pass http://location_service;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ───────── Delivery Service ─────────

        location /api/delivery {

            proxy_pass http://delivery_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ───────── Frontend ─────────

        location / {

            proxy_pass http://host.docker.internal:4000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}